/* Generated by grovel.scm */

#include <errno.h>
#include <stdio.h>
#include <string.h>

#define PR(symbol) pr(#symbol, symbol)

static void pr_all(void);

static void pr(const char *symbol, int number) {
    printf("\"%s\" %d \"%s\"\n", symbol, number, strerror(number));
}

int main(void) {
    printf("(define errno-list '(\n");
    pr_all();
    printf("))\n");
    return 0;
}

static void pr_all(void) {
    PR(E2BIG);
    PR(EACCES);
    PR(EADDRINUSE);
    PR(EADDRNOTAVAIL);
#ifdef EADV
    PR(EADV);
#endif
    PR(EAFNOSUPPORT);
    PR(EAGAIN);
    PR(EALREADY);
#ifdef EAUTH
    PR(EAUTH);
#endif
#ifdef EBADE
    PR(EBADE);
#endif
    PR(EBADF);
#ifdef EBADFD
    PR(EBADFD);
#endif
    PR(EBADMSG);
#ifdef EBADR
    PR(EBADR);
#endif
#ifdef EBADRPC
    PR(EBADRPC);
#endif
#ifdef EBADRQC
    PR(EBADRQC);
#endif
#ifdef EBADSLT
    PR(EBADSLT);
#endif
#ifdef EBFONT
    PR(EBFONT);
#endif
    PR(EBUSY);
    PR(ECANCELED);
#ifdef ECAPMODE
    PR(ECAPMODE);
#endif
    PR(ECHILD);
#ifdef ECHRNG
    PR(ECHRNG);
#endif
#ifdef ECOMM
    PR(ECOMM);
#endif
    PR(ECONNABORTED);
    PR(ECONNREFUSED);
    PR(ECONNRESET);
    PR(EDEADLK);
#ifdef EDEADLOCK
    PR(EDEADLOCK);
#endif
    PR(EDESTADDRREQ);
    PR(EDOM);
#ifdef EDOOFUS
    PR(EDOOFUS);
#endif
#ifdef EDOTDOT
    PR(EDOTDOT);
#endif
    PR(EDQUOT);
    PR(EEXIST);
    PR(EFAULT);
    PR(EFBIG);
#ifdef EFTYPE
    PR(EFTYPE);
#endif
#ifdef EHOSTDOWN
    PR(EHOSTDOWN);
#endif
    PR(EHOSTUNREACH);
#ifdef EHWPOISON
    PR(EHWPOISON);
#endif
    PR(EIDRM);
    PR(EILSEQ);
    PR(EINPROGRESS);
    PR(EINTR);
    PR(EINVAL);
    PR(EIO);
#ifdef EIPSEC
    PR(EIPSEC);
#endif
    PR(EISCONN);
    PR(EISDIR);
#ifdef EISNAM
    PR(EISNAM);
#endif
#ifdef EKEYEXPIRED
    PR(EKEYEXPIRED);
#endif
#ifdef EKEYREJECTED
    PR(EKEYREJECTED);
#endif
#ifdef EKEYREVOKED
    PR(EKEYREVOKED);
#endif
#ifdef EL2HLT
    PR(EL2HLT);
#endif
#ifdef EL2NSYNC
    PR(EL2NSYNC);
#endif
#ifdef EL3HLT
    PR(EL3HLT);
#endif
#ifdef EL3RST
    PR(EL3RST);
#endif
#ifdef ELAST
    PR(ELAST);
#endif
#ifdef ELIBACC
    PR(ELIBACC);
#endif
#ifdef ELIBBAD
    PR(ELIBBAD);
#endif
#ifdef ELIBEXEC
    PR(ELIBEXEC);
#endif
#ifdef ELIBMAX
    PR(ELIBMAX);
#endif
#ifdef ELIBSCN
    PR(ELIBSCN);
#endif
#ifdef ELNRNG
    PR(ELNRNG);
#endif
#ifdef ELOCKUNMAPPED
    PR(ELOCKUNMAPPED);
#endif
    PR(ELOOP);
#ifdef EMEDIUMTYPE
    PR(EMEDIUMTYPE);
#endif
    PR(EMFILE);
    PR(EMLINK);
    PR(EMSGSIZE);
    PR(EMULTIHOP);
    PR(ENAMETOOLONG);
#ifdef ENAVAIL
    PR(ENAVAIL);
#endif
#ifdef ENEEDAUTH
    PR(ENEEDAUTH);
#endif
    PR(ENETDOWN);
    PR(ENETRESET);
    PR(ENETUNREACH);
    PR(ENFILE);
#ifdef ENOANO
    PR(ENOANO);
#endif
#ifdef ENOATTR
    PR(ENOATTR);
#endif
    PR(ENOBUFS);
#ifdef ENOCSI
    PR(ENOCSI);
#endif
    PR(ENODATA);
    PR(ENODEV);
    PR(ENOENT);
    PR(ENOEXEC);
#ifdef ENOKEY
    PR(ENOKEY);
#endif
    PR(ENOLCK);
    PR(ENOLINK);
#ifdef ENOMEDIUM
    PR(ENOMEDIUM);
#endif
    PR(ENOMEM);
    PR(ENOMSG);
#ifdef ENONET
    PR(ENONET);
#endif
#ifdef ENOPKG
    PR(ENOPKG);
#endif
    PR(ENOPROTOOPT);
    PR(ENOSPC);
    PR(ENOSR);
    PR(ENOSTR);
    PR(ENOSYS);
#ifdef ENOTACTIVE
    PR(ENOTACTIVE);
#endif
#ifdef ENOTBLK
    PR(ENOTBLK);
#endif
#ifdef ENOTCAPABLE
    PR(ENOTCAPABLE);
#endif
    PR(ENOTCONN);
    PR(ENOTDIR);
    PR(ENOTEMPTY);
#ifdef ENOTNAM
    PR(ENOTNAM);
#endif
    PR(ENOTRECOVERABLE);
    PR(ENOTSOCK);
    PR(ENOTSUP);
    PR(ENOTTY);
#ifdef ENOTUNIQ
    PR(ENOTUNIQ);
#endif
    PR(ENXIO);
    PR(EOPNOTSUPP);
    PR(EOVERFLOW);
    PR(EOWNERDEAD);
    PR(EPERM);
#ifdef EPFNOSUPPORT
    PR(EPFNOSUPPORT);
#endif
    PR(EPIPE);
#ifdef EPROCLIM
    PR(EPROCLIM);
#endif
#ifdef EPROCUNAVAIL
    PR(EPROCUNAVAIL);
#endif
#ifdef EPROGMISMATCH
    PR(EPROGMISMATCH);
#endif
#ifdef EPROGUNAVAIL
    PR(EPROGUNAVAIL);
#endif
    PR(EPROTO);
    PR(EPROTONOSUPPORT);
    PR(EPROTOTYPE);
    PR(ERANGE);
#ifdef EREMCHG
    PR(EREMCHG);
#endif
#ifdef EREMOTE
    PR(EREMOTE);
#endif
#ifdef EREMOTEIO
    PR(EREMOTEIO);
#endif
#ifdef ERESTART
    PR(ERESTART);
#endif
#ifdef ERFKILL
    PR(ERFKILL);
#endif
    PR(EROFS);
#ifdef ERPCMISMATCH
    PR(ERPCMISMATCH);
#endif
#ifdef ESHUTDOWN
    PR(ESHUTDOWN);
#endif
#ifdef ESOCKTNOSUPPORT
    PR(ESOCKTNOSUPPORT);
#endif
    PR(ESPIPE);
    PR(ESRCH);
#ifdef ESRMNT
    PR(ESRMNT);
#endif
    PR(ESTALE);
#ifdef ESTRPIPE
    PR(ESTRPIPE);
#endif
    PR(ETIME);
    PR(ETIMEDOUT);
#ifdef ETOOMANYREFS
    PR(ETOOMANYREFS);
#endif
    PR(ETXTBSY);
#ifdef EUCLEAN
    PR(EUCLEAN);
#endif
#ifdef EUNATCH
    PR(EUNATCH);
#endif
#ifdef EUSERS
    PR(EUSERS);
#endif
    PR(EWOULDBLOCK);
    PR(EXDEV);
#ifdef EXFULL
    PR(EXFULL);
#endif
}
