(import (scheme base) (scheme file) (scheme read) (scheme write))

(define errno-symbols
  '(E2BIG
    EACCES
    EADDRINUSE
    EADDRNOTAVAIL
    EADV
    EAFNOSUPPORT
    EAGAIN
    EALREADY
    EAUTH
    EBADE
    EBADF
    EBADFD
    EBADMSG
    EBADR
    EBADRPC
    EBADRQC
    EBADSLT
    EBFONT
    EBUSY
    ECANCELED
    ECAPMODE
    ECHILD
    ECHRNG
    ECOMM
    ECONNABORTED
    ECONNREFUSED
    ECONNRESET
    EDEADLK
    EDEADLOCK
    EDESTADDRREQ
    EDOM
    EDOOFUS
    EDOTDOT
    EDQUOT
    EEXIST
    EFAULT
    EFBIG
    EFTYPE
    EHOSTDOWN
    EHOSTUNREACH
    EHWPOISON
    EIDRM
    EILSEQ
    EINPROGRESS
    EINTR
    EINVAL
    EIO
    EIPSEC
    EISCONN
    EISDIR
    EISNAM
    EKEYEXPIRED
    EKEYREJECTED
    EKEYREVOKED
    EL2HLT
    EL2NSYNC
    EL3HLT
    EL3RST
    ELAST
    ELIBACC
    ELIBBAD
    ELIBEXEC
    ELIBMAX
    ELIBSCN
    ELNRNG
    ELOCKUNMAPPED
    ELOOP
    EMEDIUMTYPE
    EMFILE
    EMLINK
    EMSGSIZE
    EMULTIHOP
    ENAMETOOLONG
    ENAVAIL
    ENEEDAUTH
    ENETDOWN
    ENETRESET
    ENETUNREACH
    ENFILE
    ENOANO
    ENOATTR
    ENOBUFS
    ENOCSI
    ENODATA
    ENODEV
    ENOENT
    ENOEXEC
    ENOKEY
    ENOLCK
    ENOLINK
    ENOMEDIUM
    ENOMEM
    ENOMSG
    ENONET
    ENOPKG
    ENOPROTOOPT
    ENOSPC
    ENOSR
    ENOSTR
    ENOSYS
    ENOTACTIVE
    ENOTBLK
    ENOTCAPABLE
    ENOTCONN
    ENOTDIR
    ENOTEMPTY
    ENOTNAM
    ENOTRECOVERABLE
    ENOTSOCK
    ENOTSUP
    ENOTTY
    ENOTUNIQ
    ENXIO
    EOPNOTSUPP
    EOVERFLOW
    EOWNERDEAD
    EPERM
    EPFNOSUPPORT
    EPIPE
    EPROCLIM
    EPROCUNAVAIL
    EPROGMISMATCH
    EPROGUNAVAIL
    EPROTO
    EPROTONOSUPPORT
    EPROTOTYPE
    ERANGE
    EREMCHG
    EREMOTE
    EREMOTEIO
    ERESTART
    ERFKILL
    EROFS
    ERPCMISMATCH
    ESHUTDOWN
    ESOCKTNOSUPPORT
    ESPIPE
    ESRCH
    ESRMNT
    ESTALE
    ESTRPIPE
    ETIME
    ETIMEDOUT
    ETOOMANYREFS
    ETXTBSY
    EUCLEAN
    EUNATCH
    EUSERS
    EWOULDBLOCK
    EXDEV
    EXFULL))

(define (disp . xs) (for-each display xs) (newline))
(define tab (make-string 4 #\space))
(define dq "\"")
(define sdq "\\\"")
(define snl "\\n")

(define (write-c-program)
  (disp "/* Generated by grovel.scm */")
  (disp)
  (disp "#include <errno.h>")
  (disp "#include <stdio.h>")
  (disp "#include <string.h>")
  (disp)
  (disp "#define PR(symbol) pr(#symbol, symbol)")
  (disp)
  (disp "static void pr(const char *symbol, int number) {")
  (disp tab "printf("
        dq "("
        sdq "%s" sdq
        " " "%d" " "
        sdq "%s" sdq
        ")" snl dq
        ", symbol, number, strerror(number));")
  (disp "}")
  (disp)
  (disp "static void pr_all(void);")
  (disp)
  (disp "int main(void) {")
  (disp tab "printf(" dq "(define errno-list '(" snl dq ");")
  (disp tab "pr_all();")
  (disp tab "printf(" dq "))" snl dq ");")
  (disp tab "return 0;")
  (disp "}")
  (disp)
  (disp "static void pr_all(void) {")
  (for-each (lambda (symbol)
              (disp "#ifdef " symbol)
              (disp tab "PR(" symbol ");")
              (disp "#endif"))
            errno-symbols)
  (disp "}"))

(define (main) (with-output-to-file "grovel.c" write-c-program))

(main)
